name: terraform-testing
on:
  repository_dispatch:
    types:
      - terraform-testing

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: initialize terraform environment
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.14.3

      - name: output terraform version
        run: terraform version

      - name: terraform init
        id: init
        run: |
          cd ./terraform
          terraform init

      - name: display tf init output
        run: echo "This is the outcome of init ${{ steps.init.outcome }}"

      - name: terraform plan
        id: plan
        run: |
          cd ./terraform
          terraform plan 

      - name: terraform apply
        id: apply
        run: |
          cd ./terraform
          terraform apply --auto-approve

      - name: display terraform outputs
        run: |
          cd ./terraform
          echo "This is the Terraform output $(terraform output teststring)"

      - name: Call terraform output
        id: tf
        run: |
          cd ./terraform
          echo ::set-output name=tf_output::$(terraform output -raw teststring)
          echo $(terraform output teststring)
          echo "Terraform init outcome ${{ steps.init.outcome }}"
          echo "Terraform plan outcome ${{ steps.plan.outcome }}"
          echo "Terraform apply outcome ${{ steps.apply.outcome }}"

      - name: echo outputs
        run: echo "this is the terraform output ${{ steps.tf.outputs.tf_output }}"

      - name: Get outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: ./terraform

      - name: Print the random string
        run: echo "The terraform random string was ${{ steps.tf-outputs.outputs.teststring }}"

      # - name: output github context
      #   run: |
      #     echo "${{ toJSON(steps) }}"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
