name: terraform-testing
on:
  repository_dispatch:
    types:
      - terraform-testing

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: initialize terraform environment
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.14.3

      - name: output terraform version
        run: terraform version

      - name: terraform init
        run: |
          cd ./terraform
          terraform init

      - name: terraform plan
        run: |
          cd ./terraform
          terraform plan 

      - name: terraform apply
        id: apply
        run: |
          cd ./terraform
          terraform apply --auto-approve

      - name: display terraform outputs
        run: |
          echo "This is the Terraform output ${{ steps.apply.outputs.teststring }}"

      - name: Call terraform output
        id: tf
        run: |
          cd ./terraform
          echo ::set-output name=tf_output::$(terraform output teststring)
          echo $(terraform output teststring)

      - name: echo outputs
        run: echo "this is the terraform output ${{ steps.tf.outputs.tf_output }}"